//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 11:31:13 AM EET 
//


package com.company.currency_info;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currencyCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="currencyCode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UAH"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="GBP"/&gt;
 *     &lt;enumeration value="JPY"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *     &lt;enumeration value="CNY"/&gt;
 *     &lt;enumeration value="RUB"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "currencyCode")
@XmlEnum
public enum CurrencyCode {

    UAH(980),
    USD(840),
    EUR(978),
    GBP(826),
    JPY(392),
    CHF(756),
    CNY(156),
    RUB(643);

    private Integer value;

    CurrencyCode(Integer value) {
        this.value = value;
    }

    public static CurrencyCode findCurrency(Integer code) {
        for (CurrencyCode cd : CurrencyCode.values()) {
            if (code.equals(cd.value)) {
                return cd;
            }
        }
        return CurrencyCode.USD;
    }

}
